name: Deploy blog from Obsidian

on:
  push:
    branches:
      - main

jobs:
  publish_job:
    runs-on: ubuntu-latest
    name: Publish Obsidian notes to Github pages
    steps:
      - uses: x1sec/obsidian-to-hugo-action@main
        with:
          vault-path: obsidian-vault
          github-token: ${{ secrets.GITHUB_TOKEN }}