name: Export Obsidian Notes to Hugo

on:
  workflow_call:
    inputs:
      vault-path: Obsidian
        required: true
        type: string
      external-repository:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache cargo plugins
        id: cache-obsidian-export
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-plugins

      - name: Install obsidian-export
        if: steps.cache-obsidian-export.outputs.cache-hit != 'true'
        uses: actions-rs/install@v0.1
        with:
          crate: obsidian-export
          version: latest

      - name: Create content directory for export
        run: mkdir -p content/posts

      - name: Create layout fix directory
        run: mkdir -p layouts/_default/_markup/

      - name: Obsidian layout fixes for images and links
        uses: actions/checkout@v3
        with:
          repository: x1sec/obsidian-to-hugo-action
          path: layout

      - name: Copy over layout fixes to correct path
        run: cp layout/layout/* layouts/_default/_markup/

      - name: Export Vault
        run: obsidian-export ./${{ inputs.vault-path }} ./content/posts
